### ISSUE TITLE
Reduce Title color height

### ISSUE THREAD

**Issue by furqankhwaja** [alessandrorossini/adcv#1]
If we are not using **\adcvtitle** in the top colored portion, how do we reduce the size of the colored portion? (reduce the height) i.e. fit only **\adcvname**

**Comment by alessandrorossini** [comment]
My apologies for the late reply. Unfortunately, the `adcv` class does not support reducing the height of the colored box. To add this feature, you would have to edit the `tikzpicture` environment in the `adcv` class. I hope it helps.
