### ISSUE TITLE
Extended version

### ISSUE THREAD

**Issue by rakehsaleem** [alessandrorossini/adcv#2]
I have forked this project and tried compiling it in extended format. As far by the code and description, it says that the CV can be tailored either in one page resume or academic extended version but i'm unable to make changes in the extended version. Can you guide me at what point can we select the extended version in the latex code ? And the other thing I noticed is that their is pdf file for extended version but no .tex file for it. How to get the .tex file for extended version sir ?
Thank you
-Rakeh

**Comment by alessandrorossini** [comment]
My apologies for the late reply. You do not need an additional tex file. To compile the extended version, you have to add the `extended` option to the `\documentclass` command, e.g., `\documentclass[a4paper,extended]{adcv}`. I hope it helps.
